<?php 
$communes = [

		"Abengourou",
		"Abie",
		"Abigui",
		"Abobo",
		"Aboisso",
		"Aboisso-Comoe",
		"Abolikro",
		"Abongoua",
		"Abongoua",
		"Aboude",
		"Abra",
		"Abradinou",
		"Abronamoue",
		"Aby (Aboisso)",
		"Aby-Adjouan-Mohoua",
		"Adaou",
		"Addah",
		"Adesse",
		"Adiake",
		"Adjame",
		"Adjamene",
		"Adjouan",
		"Adouakouakro",
		"Adoukro",
		"Adzope",
		"Affalikro",
		"Affery",
		"Affienou",
		"Afotobo",
		"Agbaou-Aheoua",
		"Agboville",
		"Agnia",
		"Agnibilekrou",
		"Agou",
		"Ahigbe-Koffikro",
		"Ahouabo-Bouape",
		"Ahouakro",
		"Ahouanou",
		"Ahougnanssou",
		"Ahougnassou-Alahou",
		"Akoboissue",
		"Akoi N'denou",
		"Akounougbe",
		"Akoupe",
		"Akoupe-Zeudji",
		"Akoure",
		"Akradio",
		"Akridou-Ladde",
		"Alepe",
		"Allangouassou",
		"Allosso 2",
		"Amanvi",
		"Amelekia",
		"Amian Kouassikro",
		"Amoriakro",
		"Ananda (Daoukro)",
		"Ananguie (Agboville), (departement d'Agboville)",
		"Ananguie (Adzope), (departement d'Adzope)",
		"Ancien Prozi, (sous-prefecture de Seitifla)",
		"Ande",
		"Ando-Kekrenou",
		"Angoda",
		"Anianou",
		"Aniassue",
		"Annepe",
		"Anno (Agboville)",
		"Anoumaba",
		"Anyama",
		"Appimandoum",
		"Appoisso",
		"Appouasso",
		"Apprompron-Afêwa",
		"Apprompronou",
		"Arikokaha",
		"Arokpa",
		"Arrah",
		"Assahara",
		"Assale-Kouassikro",
		"Assandrè",
		"Assie-Koumassi",
		"Assikoi",
		"Assinie-Mafia",
		"Assuefry",
		"Attecoube",
		"Attiegouakro",
		"Attiekoi",
		"Attiguehi",
		"Attinguie",
		"Attobrou",
		"Attokro",
		"Attoutou A",
		"Ayame",
		"Ayaou-Sran",
		"Ayenouan",
		"Azaguie",

		"Babakro",
		"Bacanda",
		"Bacon",
		"Badikaha",
		"Bagohouo",
		"Bakandesso-Sogbeni",
		"Bakanou",
		"Bako",
		"Bakoubli",
		"Baleko",
		"Bambalouma",
		"Bamoro",
		"Bandakagni Tomora",
		"Bandakagni-Sokoura",
		"Bandiahi",
		"Bangolo",
		"Bangoua",
		"Banneu",
		"Bannonfla",
		"Bassawa",
		"Baya (Kouto)",
		"Bayota",
		"Bazra-Nattis",
		"Bazre",
		"Becedi Brignan",
		"Becouefin",
		"Bediala",
		"Bedy-Goazon",
		"Begbessou",
		"Belleville, (departement de Zoukougbeu)",
		"Bengassou",
		"Beoue-Zibiao",
		"Beoumi",
		"Bereni Dialla",
		"Beriaboukro",
		"Bettie",
		"Biakale",
		"Biankouma",
		"Bianouan",
		"Biasso",
		"Bieby",
		"Bilimono",
		"Bin-Houye",
		"Binao-Boussoue",
		"Bingerville",
		"Binzra",
		"Bla",
		"Blanfla",
		"Blapleu",
		"Blenimeouin",
		"Blessegue",
		"Blolequin",
		"Blotile",
		"Boahia",
		"Bobi",
		"Bobo-Tienigbe",
		"Bocanda",
		"Bodo (Didievi), (departement de Didievi)",
		"Bodo (Tiassale), (departement de Tiassale)",
		"Bodokro",
		"Bogofa",
		"Bogouine",
		"Boguedia",
		"Bohobli",
		"Bokala-Niampondougou",
		"Boli",
		"Bolona",
		"Bonahouin",
		"Bondo",
		"Bondoukou",
		"Bongo (Grand-Bassam)",
		"Bongouanou",
		"Bonguera",
		"Bonieredougou",
		"Bonikro",
		"Bonon",
		"Bonoua",
		"Bonoufla",
		"Booko",
		"Boron (Korhogo)",
		"Borotou",
		"Borotou-Koro",
		"Botinde",
		"Botro",
		"Bouadikro",
		"Bouafle",
		"Bouandougou",
		"Bouboury",
		"Boudepe",
		"Bougou",
		"Bougousso",
		"Bouko",
		"Bouna",
		"Boundiali",
		"Boyaokro",
		"Bozi",
		"Bricolo",
		"Brihiri",
		"Brima",
		"Brobo",
		"Brofodoume",
		"Broma",
		"Brou Ahoussoukro",
		"Brou Akpaoussou",
		"Broubrou",
		"Broudoukou-Penda",
		"Buyo",

		"Cechi",
		"Chiepo",
		"Cocody",
		"Cosrou",

		"Dabadougou-Mafele",
		"Dabakala",
		"Dabou",
		"Dabouyo",
		"Dadiasse",
		"Dagba",
		"Dah-Zagna",
		"Dahiepa-Kehi",
		"Dahiri",
		"Dairo-Didizo",
		"Dakouritrohoin",
		"Dakpadou",
		"Daleu",
		"Dame",
		"Danane",
		"Dananon",
		"Dandougou",
		"Danguira",
		"Dania",
		"Danoa",
		"Dantogo",
		"Daoukro",
		"Dapeoua",
		"Dapo-Iboke",
		"Dassioko",
		"Dassoungboho",
		"Debete",
		"Dèdègbeu",
		"Detroya",
		"Diabo",
		"Diahouin",
		"Dialakoro",
		"Diamakani",
		"Diamarakro",
		"Diamba",
		"Diangobo (Abengourou), (departement d'Abengourou)",
		"Diangobo (Yakasse-Attobrou), (departement de Yakasse-Attobrou)",
		"Diangokro",
		"Dianra",
		"Dianra-Village",
		"Diarabana",
		"Diasson",
		"Diawala",
		"Dibobly",
		"Diboke",
		"Dibri-Assirikro",
		"Didievi",
		"Didoko",
		"Diegonefla",
		"Diemeressedougou",
		"Dieouzon",
		"Dieviessou",
		"Digbapia",
		"Dignago",
		"Dikodougou",
		"Dimandougou",
		"Dimbokro",
		"Dinaoudi",
		"Dingbi",
		"Dioman",
		"Dioulatièdougou",
		"Diourouzon",
		"Divo",
		"Djamadjoke",
		"Djapadji",
		"Djebonouan",
		"Djekanou",
		"Djibrosso",
		"Djidji",
		"Djoro-Djoro",
		"Djouroutou",
		"Doba",
		"Dobre",
		"Dogbo",
		"Doh (Touba)",
		"Doke",
		"Domangbeu",
		"Doropo",
		"Douèle",
		"Dougroupalegnoa",
		"Doukouya",
		"Doukouyo",
		"Dousseba",
		"Dribouo",
		"Dualla",
		"Duekoue",
		"Duffrebo",
		"Duonfla",
		"Dzeudji",

		"Ebikro-N’dakro",
		"Ebilassokro",
		"Ebonou",
		"Eboue (Aboisso)",
		"Ehuasso",
		"Ellibou-Badasso",
		"Eloka",
		"Ettrokro",
		"Etueboue",
		"Etuessika",

		"Facobly",
		"Fadiadougou",
		"Famienkro",
		"Fapaha-M’binguebougou",
		"Faraba (Mankono)",
		"Fengolo",
		"Feremandougou",
		"Ferentela",
		"Ferkessedougou",
		"Finessiguedougou",
		"Fizanlouma",
		"Flakièdougou",
		"Foto-Kouamekro",
		"Foumbolo",
		"Foungbesso",
		"Frambo",
		"Fresco",
		"Fronan",

		"Gabia (Issia), (departement d'Issia)",
		"Gabia (Oume), (departement d'Oume)",
		"Gabiadji",
		"Gadago",
		"Gagnoa",
		"Gagny",
		"Galebou",
		"Ganaoni",
		"Ganhoue",
		"Ganleu",
		"Gaote",
		"Gbablasso",
		"Gbadjie",
		"Gbagbam",
		"Gbameledougo",
		"Gbangbegouine",
		"Gbangbegouine-Yati",
		"Gbapleu",
		"Gbatongouin",
		"Gbazoa",
		"Gbèkèkro",
		"Gbeleban",
		"Gbetogo",
		"Gbliglo",
		"Gbofesso-Sama",
		"Gbogolo",
		"Gboguhe",
		"Gbon",
		"Gbon-Houye",
		"Gbongaha",
		"Gbonne",
		"Glangleu",
		"Gligbeuadji",
		"Gloplou",
		"Gnagbodougnoa",
		"Gnagboya",
		"Gnago",
		"Gnakouboue",
		"Gnamanou",
		"Gnato",
		"Gnegrouboue",
		"Gnogboyo",
		"Godelilie 1",
		"Gogne",
		"Gogo",
		"Gogoguhe",
		"Gohitafla",
		"Gohouo-Zagna",
		"Gomon",
		"Gonate",
		"Gopoupleu",
		"Gotongouine 1",
		"Gouane",
		"Goudi",
		"Goudouko",
		"Gouekan",
		"Gouenzou",
		"Gouine",
		"Goulaleu",
		"Goulia",
		"Goumere",
		"Gouotro",
		"Gourane",
		"Gra",
		"Grabo",
		"Gragba-Dagolilie",
		"Grand Alepe",
		"Grand-Bassam",
		"Grand-Bereby",
		"Grand-Lahou",
		"Grand-Morie",
		"Grand-Pin",
		"Grand-Yapo",
		"Grand-Zattry",
		"Grand-Akoudzin",
		"Gregbeu",
		"Grihiri",
		"Grobiakoko",
		"Grobonou-Dan",
		"Guehiebly",
		"Guekpe",
		"Guenimanzo",
		"Guepahouo",
		"Guessabo",
		"Guessiguie",
		"Gueyo",
		"Guezon (Duekoue) (departement de Duekoue)",
		"Guezon (Kouibly) (departement de Kouibly)",
		"Guezon-Tahouake",
		"Guiamapleu",
		"Guiberoua",
		"Guiembe",
		"Guiende",
		"Guiglo",
		"Guimeyo",
		"Guinglo-Gbean",
		"Guinglo-Tahouake",
		"Guinteguela",
		"Guitry",

		"Herebo",
		"Hermankono-Diès",
		"Hermankono-Garo",
		"Hire",
		"Huafla",

		"Iboguhe",
		"Iboke",
		"Idibouo-Zepreguhe (Daloa Est)",
		"Ipouagui",
		"Iriefla",
		"Irobo",
		"Iroporia",
		"Issia",

		"Jacqueville",

		"Kaade",
		"Kadeko",
		"Kadioha",
		"Kafoudougou-Bambarasso",
		"Kagbolodougou",
		"Kahin-Zarabaon",
		"Kakpi",
		"Kalaha",
		"Kalamon",
		"Kaloa",
		"Kamala",
		"Kamalo",
		"Kamoro",
		"Kanagonon",
		"Kanakono",
		"Kanawolo",
		"Kani",
		"Kaniasso",
		"Kanoroba",
		"Kanzra",
		"Kaouara",
		"Karakoro",
		"Kassere",
		"Katchire-Essekro",
		"Katiali",
		"Katimassou",
		"Katiola",
		"Kato (Seguela)",
		"Katogo",
		"Kawolo-Sobara",
		"Ke-Bouebo",
		"Kebi",
		"Keibla",
		"Keibly",
		"Ketesso",
		"Ketro-Bassam",
		"Kibouo",
		"Kiele",
		"Kiemou",
		"Kimbirila Nord",
		"Kimbirila Sud",
		"Klan",
		"Kodiossou",
		"Koffi-Amonkro",
		"Koffikro-Affema",
		"Koko (Bouake), (departement de Bouake)",
		"Koko (Korhogo), (departement de Korhogo)",
		"Kokolopozo",
		"Kokomian",
		"Kokoumba",
		"Kokoun",
		"Kokumbo",
		"Kolia",
		"Kombolokoura",
		"Komborodougou",
		"Konan Kokorekro",
		"Konan-N’drikro",
		"Konandikro",
		"Kondiebouma",
		"Kondokro-Djassanou",
		"Kondossou",
		"Kondrobo",
		"Kong",
		"Kongasso",
		"Kongoti",
		"Koni",
		"Kononfla",
		"Koonan",
		"Koreahinou",
		"Koro",
		"Korhogo",
		"Korokaha",
		"Korokopla",
		"Koroumba",
		"Kossandji",
		"Kossehoa",
		"Kossihouen",
		"Kossou",
		"Kotobi",
		"Kotogwanda",
		"Kotronou",
		"Koua",
		"Kouadioblekro",
		"Kouadiokro",
		"Kouafo-Akidom",
		"Kouakro",
		"Kouamefla",
		"Kouan-Houle",
		"Kouassi-Datèkro",
		"Kouassi Kouassikro",
		"Kouassi-N’Dawa",
		"Kouassia-Nanguni",
		"Kouatta",
		"Koudougou",
		"Kouetinfla",
		"Kouibly",
		"Koulale",
		"Koulikoro (Biankouma)",
		"Koumassi",
		"Koumbala",
		"Koun-Fao",
		"Kounahiri",
		"Kounzie",
		"Kouto",
		"Koutouba",
		"Koutoukro 1 bord",
		"koutoukro 2",
		"Koyekro",
		"Koziayo 1",
		"Kpada",
		"Kpana-Kalo",
		"Kpanan",
		"Kpanpleu-Sin-Houye",
		"Kpapekou",
		"Kpata",
		"Kpèbo",
		"Kpotè",
		"Kpouèbo",
		"Kregbe",
		"Kreuzoukoue",
		"Krindjabo",
		"Krofoinsou",

		"Labokro",
		"Lafokpokaha",
		"Lahou Kpandah",
		"Lahouda",
		"Lakota",
		"Lamekaha (Ferkessedougou), (departement de Ferkessedougou)",
		"Lamekaha (Korhogo), (departement de Korhogo)",
		"Landiougou",
		"Languibonou",
		"Laoudi-Ba",
		"Larabia",
		"Lataha",
		"Lauzoua",
		"Leleble",
		"Lengbrè",
		"Lessiri",
		"Ligrohoin",
		"Liliy",
		"Lissolo-Sobara",
		"Lobakuya",
		"Lobogba",
		"Logbonou",
		"Logouale",
		"Logroan (Daloa Sud)",
		"Lolobo (Beoumi), (departement de Beoumi)",
		"Lolobo (Yamoussoukro), (departement de Yamoussoukro)",
		"Lomokankro",
		"Lopou",
		"Loukou-Yaokro",
		"Loviguie",
		"Luenoufla",

		"M’bahiakro",
		"M’batto",
		"M’bengue",
		"M’bonoua",
		"M’Borla-Dioulasso",
		"M’brou",
		"M’possa",
		"Mabehiri 1",
		"Mabouo",
		"Madinani",
		"Mafere",
		"Maguehio",
		"Mahale",
		"Mahandiana Soukourani",
		"Mahandougou",
		"Mahapleu",
		"Mahino",
		"Makey-Liboli",
		"Mamini",
		"Maminigui",
		"Man",
		"Manabri",
		"Mandougou",
		"Manfla",
		"Mangouin-Yrongouin",
		"Mankono",
		"Mantongouine",
		"Manzanouan",
		"Marabadiassa",
		"Marandallah",
		"Marcory",
		"Massadougou",
		"Massala (Seguela)",
		"Massala-Barala",
		"Mayo",
		"Meagui",
		"Medon",
		"Mekro",
		"Memni",
		"Meneke",
		"Meo",
		"Miadzin",
		"Mignore",
		"Minfla",
		"Minignan",
		"Moape",
		"Molonou",
		"Molonou-Ble",
		"Momirasso",
		"Monga",
		"Mongbara",
		"Monoko Zohi",
		"Monongo",
		"Mont Korhogo",
		"Morokinkro",
		"Morokro",
		"Morondo",
		"Moronou",
		"Moussobadougou",

		"N’dakro",
		"N’denou",
		"N’deou",
		"N’douci",
		"N’douffoukankro",
		"N’doukahakro",
		"N’gangoro-Attoutou",
		"N’Ganon",
		"N’Gattadolikro",
		"N’Gattakro",
		"N’Gban Kassê",
		"N’gohinou",
		"N’Goloblasso",
		"N’gribo-Takikro",
		"N’guessan-Brindoukro",
		"N’Guessankro (Beoumi), (departement de Beoumi)",
		"N’Guessankro (Bongouanou), (departement de Bongouanou)",
		"N’guieme",
		"N’Guyakro",
		"N’Zecrezessou",
		"N’Zi-N’Ziblekro",
		"N’Zianouan",
		"N’Zue-Kokore",
		"Nafana (Ferkessedougou), (departement de Ferkessedougou)",
		"Nafana (Prikro), (departement de Prikro)",
		"Nafana Sienso",
		"Nafoun",
		"Nahio",
		"Namahounondougou",
		"Namane",
		"Namassi",
		"Nambingue",
		"Nandjele-Segbere",
		"Napie",
		"Nassian",
		"Nebo (Divo)",
		"Neguepie",
		"Neko",
		"Nezobly",
		"Niable",
		"Niakaramandougou",
		"Niakoblognoa",
		"Niamana (Odienne)",
		"Niambezaria",
		"Niazaroko",
		"Nidrou",
		"Niediekaha",
		"Nielle",
		"Niemene",
		"Nigui Assoko",
		"Nigui Saff",
		"Niofoin",
		"Niokosso",
		"Niorouhio",
		"Nioulde",
		"Nizahon",
		"Noe (Tiapoum)",
		"Nofou",
		"Nouamou",
		"Odienne",
		"Offa (Agboville)",
		"Offoumpo",
		"Oghlwapo",
		"Ogoudou",
		"Okrouyo",
		"Olodio",
		"Ondefidouo",
		"Ono",
		"Orbaff",
		"Oress-Krobou",
		"Ottawa",
		"Ottope",
		"Ouangolodougou",
		"Ouaninou",
		"Ouattaradougou",
		"Ouedallah",
		"Ouelle",
		"Oueoulo",
		"Ouffouediekro",
		"Oume",
		"Oupoyo",
		"Ouragahio",
		"Oureguekaha",
		"Ousrou",
		"Ouyably-Gnondrou",

		"Pacobo",
		"Pakouabo",
		"Pambasso-Diedou",
		"Pangalakaha",
		"Paoufla",
		"Papara (Tengrela)",
		"Para (Tabou)",
		"Pauly",
		"Peguekaha",
		"Pehe",
		"Pehekanhouebli",
		"Pelezi",
		"Petigoa 2",
		"Petit Guiglo",
		"Pinda-Boroko",
		"Pinhou",
		"Pitiengomon",
		"Plateau",
		"Pleuro",
		"Podiagouine",
		"Podoue",
		"Pogo (Ouangolodougou)",
		"Pokreagui",
		"Ponondougou",
		"Port-Bouët",
		"Poumbly",
		"Pranouan",
		"Prikro",

		"Raviart",
		"Roa",
		"Rubino",

		"Saboudougou",
		"Sago",
		"Sahebo",
		"Sahuye",
		"Saïoua",
		"Sakassou",
		"((Sakahouo))",
		"Sakre",
		"Samango",
		"Samanza",
		"Samatiguila",
		"Saminikro",
		"San-Pedro",
		"Sandala",
		"Sandegue",
		"Sandougou-Soba",
		"Sangouine",
		"Sankadiokro",
		"Santa (Biankouma) (departement de Biankouma)",
		"Santa (Touba) (departement de Touba)",
		"Sapli-Sepingo",
		"Sarhala",
		"Sassako Begnini",
		"Sassandra",
		"Satama-Sokoro",
		"Satama-Sokoura",
		"Satikran",
		"Satroko",
		"Sebedoufla",
		"Seguela",
		"Seguelon",
		"Seileu",
		"Seitifla",
		"Semien",
		"Sepikaha",
		"Serebissou",
		"Serihi",
		"Seydougou",
		"Sianhala",
		"Siansoba",
		"Siempurgo",
		"Sifie",
		"Sikensi",
		"Sikolo",
		"Silakoro",
		"Sinematiali",
		"Sinfra",
		"Singo",
		"Siolokaha",
		"Sipilou",
		"Sirana",
		"Sirasso",
		"Siriho",
		"Sissedougou",
		"Soaekpe-Douedy",
		"Soba (Korhogo)",
		"Soba-Banandje",
		"Sohouo",
		"Sokala-Sobara",
		"Sokoro",
		"Sokorodougou",
		"Sokourala-Mahou",
		"Sokrogbo",
		"Sokrogbo-Carrefour",
		"Sominasse",
		"Somokoro",
		"Songan",
		"Songon",
		"Songori",
		"Sononzo",
		"Sorobango",
		"Soubre",
		"Soukourougban",
		"Soungassou",
		"Subiakro",

		"Taabo",
		"Taabo-Village",
		"Tabagne",
		"Tabayo 1",
		"Tableguikou",
		"Taboth",
		"Tabou",
		"Tafire",
		"Tagadi",
		"Tahakro",
		"Tahibly",
		"Taï",
		"Takikro",
		"Takoreagui",
		"Talahini Tomora",
		"Tambi",
		"Tanda",
		"Tangafla",
		"Tanguelan",
		"Tankesse",
		"Taoudi",
		"Tapeguia",
		"Tawara",
		"Teapleu",
		"Teguela",
		"Tehini",
		"Tehiri",
		"Tendene-Bambarasso",
		"Tengrela",
		"Tezie",
		"Tiagba",
		"Tiapoum",
		"Tiassale",
		"Tibeita",
		"Tie N’diekro",
		"Tiebissou",
		"Tiedio",
		"Tiegba",
		"Tiekpe",
		"Tieme",
		"Tiemelekro",
		"Tienindieri",
		"Tieningboue",
		"Tienko (departement de Minignan)",
		"Tienko (departement de Touba)",
		"Tienkoikro",
		"Tieny-Seably",
		"Tieole-Oula",
		"Tieviessou",
		"Timbe",
		"Tinhou",
		"Tiobly",
		"Tioro",
		"Tofla",
		"Togoniere",
		"Toliesso",
		"Tomono",
		"Tonla",
		"Torossanguehi",
		"Tortiya",
		"Totrodrou",
		"Touba",
		"Toubalo",
		"Tougbo",
		"Touih",
		"Toukouzou",
		"Toulepleu",
		"Toumodi",
		"Toumodi-Sakassou",
		"Toumoukoro",
		"Toupah",
		"Toutoubre",
		"Trafesso",
		"Transua",
		"Treichville",

		"Vaafla",
		"Vao",
		"Varale",
		"Vavoua",
		"Voueboufla",

		"Walèbo",
		"Wate",
		"Wonsealy",
		"Worofla",

		"Yaakro",
		"Yabayo",
		"Yacolidabouo",
		"Yakasse-Attobrou",
		"Yakasse-Feyasse",
		"Yakasse-Me",
		"Yakpabo-Sakassou",
		"Yala (Vavoua)",
		"Yamoussoukro",
		"Yaossedougou",
		"Yaou",
		"Yapleu",
		"Yelleu",
		"Yeretiele",
		"Yezimala",
		"Yobouakro",
		"Yocoboue",
		"Yokorea",
		"Yoouredoula",
		"Yopohue",
		"Yopougon",
		"Yorobodi",
		"Yorodougou",
		"Yrozon",

		"Zagne",
		"Zagoreta-Gadouan",
		"Zagoue (Man)",
		"Zaguieta",
		"Zaguinasso",
		"Zahia",
		"Zaïbo",
		"Zakoeoua",
		"Zaliohouan",
		"Zambakro",
		"Zanzansou",
		"Zanzra",
		"Zaranou",
		"Zatta",
		"Zeaglo",
		"Zebouo Nord (Daloa Nord)",
		"Zebra",
		"Zede-Dianhoun",
		"Zego",
		"Zemenafla-V",
		"Zeo",
		"Zeregbo",
		"Zialegrehoa (Grand-Zia)",
		"Ziki-Diès",
		"Zikisso",
		"Ziogouine",
		"Zirifla",
		"Zokoguh'e",
		"Zonneu",
		"Zorofla",
		"Zou",
		"Zouan-Hounien",
		"Zouatta",
		"Zougounefla",
		"Zoukougbeu",
		"Zoukpangbeu",
		"Zoupleu",
		"Zraluo",
		"Zro",
		"Zuenoula",
		];
